c360: customer
ccpl: customer
crcp: restaurant
d3po: sales
daap: platform
desg: esg
dmas: misc
dops: platform
dppt: platform
dqdm: platform
dret: platform
dsal: sales
e2et: customer
f360: finance
fdct: platform
fipl: finance
inpl: platform
lods: restaurant
mcdp: customer
mdcs: sales
msot: sales
pace: restaurant
peak: restaurant
plex: sales
prpl: restaurant
rest: restaurant
rops: platform
rpip: sales
schn: supplychain
sdbx: platform
seru: customer
t360: misc
vsta: sales
